### ISSUE TITLE
Error when creating identities.

### ISSUE THREAD

**Issue by RockLloque** [huhn511/iota-identity-js-workshop#2]
When running the code (02_create_did.js) I get the following error:
```node:buffer:712
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined
    at new NodeError (node:internal/errors:259:15)
    at Function.byteLength (node:buffer:712:11)
    at passStringToWasm0 (path/Iota/iota-identity-js-workshop/node_modules/iota-identity-wasm-test/node/iota_identity_wasm.js:57:24)
    at new Key (path/Iota/iota-identity-js-workshop/node_modules/iota-identity-wasm-test/node/iota_identity_wasm.js:818:20)
    at Object.<anonymous> (path/Iota/iota-identity-js-workshop/src/02_create_did.js:5:23)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:72:12) {
  code: 'ERR_INVALID_ARG_TYPE```

**Comment by huhn511** [comment]
Fixed and extended the example. You can run it with

`node src/02_create_did_and_doc`

**Comment by RockLloque** [comment]
Thank you, now it works flawlessly!
